# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rWylgm9Sc1e2F1jfsMtk3iYRiQGVCEVt
"""

data = []
choice = 'random'

def line():
    print('------------------------')

def show_menu():
    line()
    print('Choice MENU')
    line()
    print('Choose 1. to add Semester Course')
    print('Choose 2. to remove or unenroll a Course')
    print('Choose 3. to View  all Courses')
    print('Choose 4. to exit')
    line()
    choice = input('Enter your choice: ')
    return choice

while choice != '4':
    choice = show_menu()
    if choice == '1':
        course = input('Enter a course name you want to add? ')
        data.append(course)
        print('Course', course, 'added successfully!')
    elif choice == '2':
        course = input('Which course you want to remove or unenroll from list? ')
        if course in data:
            data.remove(course)
            print('Removed course', course)
        else:
            print('Could not find course', course)
    elif choice == '3':
        print('List of courses:')
        for course in data:
            print(course)
    elif choice == '4':
        print('Goodbye!')
    else:
        print('Please enter one of 1, 2, 3 or 4')